<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- <link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" /> -->
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色 -->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	
	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<!--	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>  -->
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
    	
	<!-- datatable的js -->
<!--	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>-->
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<script src="../../scripts/app.js" type="text/javascript"></script>
	<script type="text/javascript" src="../../assets/wgy/showAllVersionOfCase.js"></script>

	<script type="text/javascript">


	</script>

	<style type="text/css">

.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
</style>
</head>
<body>
<div class="www">
		<!-- <h3 class="page-title">
				<?php echo $casename?>所有的版本 <small>from zwcs</small>
		</h3>
		<input type="text" style="display:none" value="<?php echo $case_id?>" id="case_id"/> -->
		<h3 class="page-title">
				<?php echo $game_name?>所有的案例 <small>from zwcs</small>
		</h3>

<!-- search -->

	<div style="">
  		<div style="float:left">
    		<input type="text" style="width:400px" class=" form-control" id="search">
  		</div>
  		<div style="float:left"><a href="#" id="btnSearch" class="btn green">搜索</a></div>

	</div>
<br></br>
<div id="research" class="row" style="display:none">
	<div class='col-md-6' style="float:left">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-reorder"></i>搜索筛选
				</div>
<!-- 				<div class="tools">
					<a href="javascript:;" class="collapse"></a>
				</div> -->
			</div>
			<div class="portlet-body">
			<!-- </div> -->
			<div class="row">
				<div class='col-md-4'>
					<ul><input name="content" type="checkbox" value="title">标题</ul>
					<ul><input name="content" type="checkbox" value="Initial_condition">初始条件</ul>
					<ul><input name="content" type="checkbox" value="procedures">操作</ul>
					<ul><input name="content" type="checkbox" value="expected_result">期望结果</ul>
				</div>
				<div  class='col-md-5'>	
					<ul>创建者<input type="text" class="form-control" id="author"/></ul> 
				</div>
				<div style="float:left;margin-top:80px" ><a href="#" id="btnResearch" class="btn blue">从结果中查询</a></div>
			</div>
			</div>
		</div>
	</div>
</div>
<!-- search-->


<div class="portlet box blue">
<div class="portlet-title">
	<div class="caption"><i class="fa fa-globe"></i>所有案例
	</div>
		<div class="actions">
			<a id="delete" class="btn blue" href="#" onClick="fnDeleteRow();">
				<i class="fa fa-minus"></i>
				删除
			</a>
			<a class="btn blue" href="#" onClick="reload();">
				<i class="fa fa-refresh"></i>
				刷新
			</a>
	</div>
</div>
<div class="portlet-body">
<div id="casesTable">
 <div class="table-container">
<table class="table table-striped table-bordered table-hover" id="table_id" >
	<thead></thead>
	<tbody></tbody>
	<tfoot></tfoot>
</table>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
