<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色 -->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!--
	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
    -->	
	<!-- datatable的js -->
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<script type="text/javascript" src="../../assets/chengh/showCaseByTask.js"></script>
	<style type="text/css">

.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
</style>
</head>
<body>
<div class="www">
		<h3 class="page-title">
				【<?php echo $task_name?>】所有的案例 <small>from zwcs</small>
		</h3>
		<input type="text" style="display:none" value="<?php echo $task_id?>" id="task_id"/>


<!-- CRUD按钮 -->
<div class="portlet box blue">
<div class="portlet-title">
	<div class="caption"><i class="fa fa-globe"></i>详情<a class="btn blue" href="../../task/task/showallottasks?game_v_id=<?php echo $game_v_id?>" target="page_iframe">
			<i class="fa fa-reply"></i>
			返回上一层</a></div>
	<div class="actions">
		<a class="btn blue"  onClick="reload();">
		<i class="fa fa-refresh"></i>
				刷新
		</a>
	</div>
</div>
<div class="portlet-body">
 <div class="table-container">
<table class="table table-striped table-bordered table-hover" id="table_id" >
	<thead>	
		<tr role="row" class="heading">
			<th width="20%">案例</th>
			<th>版本</th>
			<th width="5%">用例总数</th>
			<th width="5%">通过条数</th>
			<th width="5%">失败条数</th>
			<th>创建时间</th>
<!-- 			<th>提交时间</th> -->
			<th>创建者</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot></tfoot>
</table>
</div>
</div>
</div>
</div>
</body>
</html>
