<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色 -->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<!--
	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
    -->	
	<!-- datatable的js -->
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<script type="text/javascript" src="../../assets/chengh/showCasesUnderTask.js"></script>
	<script type="text/javascript" src="../../assets/zhoujx/search.js"></script>
	<style type="text/css">

.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
</style>

	<script>
		jQuery(document).ready(function() {   
		
		    Case.init();


		});
	</script>
</head>
<body ><!--onselectstart="return false" 禁止选中-->
<div class="www">
	<input type="text" value='<?php echo $task_id ?>' id="task_id" style="display:none"/>
	<input type="text" value='<?php echo $gameVersionId?>' id="game_v_id" style="display:none"/>
		<h3 class="page-title">
				<?php echo $task_name?> 下案例 <small>from zwcs</small>
		</h3>





	<div >
  		<div style="float:left;margin-bottom:2px">
    		<input id="search" type="text" style="width:400px" class=" form-control" >
  		</div>
  		<div id="searchCk" style="float:left"><a href="#"  class="btn green">搜索</a></div>

	</div>





<!-- CRUD按钮 -->
<div class="portlet box blue">
<div class="portlet-title">
	<div class="caption"><i class="fa fa-globe"></i>任务下所有的案例<a class="btn blue" href="../../task/task/showmyalltasks" style="margin-left:5px;padding:0" target="page_iframe">
			<i class="fa fa-reply"></i>
			返回上一层</a></div>
		<div class="actions">

<!-- 		<a id="search" class="btn blue" href="../search/tosearch?task_id=<?php echo $task_id?>&gameVersionId=<?php echo $gameVersionId?>" target='page_iframe'>
			<i class="fa fa-plus"></i>
			搜索
		</a> -->

		<a id="importexcel" class="btn blue" href="../../excel/excelopera/excelinputview?task_id=<?php echo $task_id?>&gameVersionId=<?php echo $gameVersionId?>" target='page_iframe'>
			<i class="fa fa-plus"></i>
			导入
		</a>
		<a id="delete" class="btn blue" href="#" onClick="fnDeleteRow();">
			<i class="fa fa-minus"></i>
			删除
		</a>
		 
		<!-- *************************************************************************************************************************** -->
		<a class="btn blue" href="#" onClick="reload();">
			<i class="fa fa-refresh"></i>
			刷新
		</a>
		</div>
</div>
<div class="portlet-body">

 <div class="table-container">
<table class="table table-striped table-bordered table-hover" id="table_id" >
	<thead>	
		<tr role="row" class="heading">
			<th  width="10%">案例ID</th>
			<th   width="20%">案例名</th>
			<th   width="5%">案例版本</th>
			<th   width="10%">创建时间</th>
			<!-- <th  width="10%">是否已提交</th> -->
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot></tfoot>
</table>


						<div id = "search_re" class = "search_re">
							
						</div>
						<div id = "detail" class = "detail_re" style="display:none;">
							<!-- <div  class = "detail_re detail_one">
								<div  class = " detail_v">用例版本ID</div>
								<div  class = " detail_v">用例TC_ID</div>
								<div  class = " detail_v">titile</div>
								<div  class = " detail_v">初始条件</div>
								<div  class = " detail_v">操作方法</div>
								<div  class = " detail_v">期望结果</div>
							</div> -->

						</div>


</div>
</div>
</div>
</div>
</body>
</html>
