<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0.2
Version: 1.5.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>Test Case</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->          
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES --> 
	<!--<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />--> 
	<!-- END PAGE LEVEL SCRIPTS -->
	<!-- BEGIN THEME STYLES --> 
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	<!-- END THEME STYLES -->
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<link href="../../assets/css/search.css" rel="stylesheet" type="text/css"/>
	<script type="text/javascript" src="../../assets/zhoujx/search.js"></script>
	<link rel="shortcut icon" href="favicon.ico" />
	<style>
	html { overflow-x:hidden; }
	.content{height:100%; background:#ffffff; position:absolute; width:100%;} 
	</style>
	<script>
		jQuery(document).ready(function() {   
		
		    Case.init();


		});
	</script>
	<!-- END PAGE LEVEL SCRIPTS -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed" height="100%" >
			 <div id="game_v_id" style="display:none;"><?php echo $game_v_id; ?></div>
			 <div id="task_id" style="display:none;"><?php echo $task_id; ?></div>
	<div class="content">							
			<!-- BEGIN PAGE CONTENT-->
			<div class="row" >
				<div class="col-md-12">
					<div class="portlet box blue" id="form_wizard_1">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-reorder"></i>用例搜索<span class="step-title"></span>
							</div>
							<div class="tools hidden-xs">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="form-actions fluid">
							<div class="row">
								<div class="col-md-12">
									<div class="search_box" style="float:left"> 
											<div class="search_form"> 
												<input type="text" id="search" class="s" placeholder="搜索内容" class="swap_value" /> 
												<input type="image" id="searchCk" src="../../assets/img/btn_search_box.gif" width="27" height="24" class="go" alt="搜索内容" title="搜索内容" /> 
											</div> 
									</div> 
										<div style="float:right;margin-right:70%">
											<div id="returnsearch" display="none;" style="margin-left:100px;margin-top:5px;float:left;display:none;"><a><font color="#1d943b">返回用例版本列表</font></a></div> 
										</div>
								</div>
							</div>
						</div>
						<div id = "search_re" class = "search_re">
							
						</div>
						<div id = "detail" class = "detail_re" style="display:none;">
							<!-- <div  class = "detail_re detail_one">
								<div  class = " detail_v">用例版本ID</div>
								<div  class = " detail_v">用例TC_ID</div>
								<div  class = " detail_v">titile</div>
								<div  class = " detail_v">初始条件</div>
								<div  class = " detail_v">操作方法</div>
								<div  class = " detail_v">期望结果</div>
							</div> -->

						</div>
					</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->   
		<!-- END PAGE -->  
	</div>
</body>
<!-- END BODY -->
</html>