<html>
	
	<head>
		<title>数据对比</title>
	</head>
		<frameset cols="50%,*" bordercolor="#3E77B3" id="myFrame">
			<!-- <frame src="showfirstcase?case_v_id=<?php echo $firstCaseVersionId?>" name="showthis" bordercolor="#3E77B3">
			<frame src="showsecondcase?case_v_id=<?php echo $secondCaseVersonId?>" name="showOthers"> -->

			<frame src="showdetailtestcase?case_v_id=<?php echo $firstCaseVersionId?>" name="showthis" bordercolor="#3E77B3">
			<frame src="showdetailtestcase?case_v_id=<?php echo $secondCaseVersonId?>" name="showOthers">
		</frameset>
</html>