<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色-->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<!-- 	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script> -->
<!-- 	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>   -->
<!-- 	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script> -->
	<!-- datatable的js -->
<!-- 	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script> -->
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<script type="text/javascript" src="../../assets/wgy/showdetailtestcase.js"></script>
	
<style type="text/css">
.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
</style>
</head>	
<body>
<div class="www">
		<h3 class="page-title">
						<?php echo $caseImf[2].$caseImf[1] ?>测试用例列表 <small>form zwcs</small>
		</h3>
<input type="text" style="display:none" value="<?php echo $case_v_id?>" id="case_v_id"/>

<!-- 对话框 -->
<form id="in_form" action="#" method="post" class="form-horizontal form-bordered" onsubmit="javascript:return false;">
<div class="form-body">
	<div class="modal fade in modal-overflow " id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog" style="width: 750px; height: 550px">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">创建测试用例</h4>
						</div>
						<div class="modal-body">
							<div class="row">
									<div class="col-md-6">
										<input type="text" style="display: none"  id="tc_id" required='required'/>
										<!-- <input type="text" style="display: none"  id="case_v_id" />等待前次操作数据 --> 
										<h5>标题</h5>
										<p><input class="col-md-6 form-control " type="text"  id="title" required="required"></p>
										
										<h5>初始条件</h5>
										<p><input class="col-md-6 form-control " type="text"  id="initial_condition" required="required" ></p>
										
										<h5>具体操作</h5>
										<p><textarea class="form-control" rows="3" id="procedure" required="required"></textarea></p>
										<h5>期望结果</h5>
										<p><input class="col-md-6 form-control " type="text" id="expected_result" required="required"></p>
									</div>	
						
							</div>						
						</div>
						<div class="modal-footer">
						  <button  id="submitbtn" type="button"  class="btn blue"  data-dismiss="modal" >保存</button> 	
							<button  id="closebtn" type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
</div>		
</form>
<!-- 对话框 -->

<!-- CRUD按钮 -->
<div class="portlet box blue">
<div class="portlet-title">
	<div class="caption"><i class="fa fa-globe"></i><?php echo $caseImf[2]?>用例详细信息<a class="btn blue" href="../../case/testcase/showallversionofcase" style="margin-left:5px;padding:0" target="page_iframe">
		<i class="fa fa-reply"></i>
		返回上一层</a></div>
		<div class="actions">
			<a  id="addbtn" class="btn blue" href="#portlet-config"  data-toggle="modal" class="config"  onClick="clearForm();">
				<i class="fa fa-plus"></i>
				新建用例
			</a>
			<a id="editbtn" class="btn blue" href="#portlet-config"  data-toggle="modal" class="config" onClick="changeClickEvent();" style="display:none">
				<i class="fa fa-edit"></i>
				Edit
			</a>
			<a id="delete" class="btn blue" href="#" onClick="fnDeleteRows();">
				<i class="fa fa-minus"></i>
				删除用例
			</a>
			<a id="delete" class="btn blue" href="#" onClick="exportCases();">
				<i class="fa fa-download"></i>
				导出
			</a>
			<a class="btn blue" href="#" onClick="reload();">
				<i class="fa fa-refresh"></i>
				刷新
			</a>
		</div>
</div>
<div class="portlet-body">

<table class="table table-striped table-bordered table-hover" id="table_id" >
	<thead id="thead"></thead>
	<tbody id="tbody"></tbody>
	<tfoot></tfoot>
</table>
<a id="goTop" href="#top"></a>
</div>
</div>
</div>
</body>
</html>