<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0.2
Version: 1.5.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>Test Case</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->          
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES --> 
	<!--<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />--> 
	<!-- END PAGE LEVEL SCRIPTS -->
	<!-- BEGIN THEME STYLES --> 
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	<!-- END THEME STYLES -->
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="../../assets/zhoujx/zhouuser.js"></script>
	<link rel="shortcut icon" href="favicon.ico" />
	<style>
	html { overflow-x:hidden; }
	.content{height:100%; background:#ffffff; position:absolute; width:100%;} 
	</style>
	<!-- END PAGE LEVEL SCRIPTS -->
	<script src="../../assets/zhoujx/menusort-click.js" type="text/javascript"></script> 
	<script>
		jQuery(document).ready(function() {   
		//start get the menu ajax
			$.ajax({ 
		        type: "GET",
		        url: "sortmenu", 
		        dataType: "json", 
		        success: function(array){ 
		            if(array['state']=="success"){
		  			$("#username").text(array['username']);
		  				 MenusortClick.init(array);//load menu
		            }else{
		            if(array['state']=='unlogin')
				        {
					        alert(array['error']);
					        top.location='../../login/Login/login';
				        }
			   		}
		   				
		        }
			}); 
		});
	</script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed" height="100%" >
	<div class="content">							
			<!-- BEGIN PAGE CONTENT-->
			<div class="row" >
				<div class="col-md-12">
					<div class="portlet box blue" id="form_wizard_1">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-reorder"></i>菜单排序<span class="step-title"></span>
							</div>
							<div class="tools hidden-xs">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="form-actions fluid">
							<div class="row">
								<div class="col-md-12">
								</div>
							</div>
						</div>

						sortmenu:
							<div  id="sort_menu" style="background:#fff; color:#000">



					</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->   
		<!-- END PAGE -->  
	</div>
</body>
<!-- END BODY -->
</html>