<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0.2
Version: 1.5.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>Test Case</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->          
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES --> 
	<!--<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />--> 
	<!-- END PAGE LEVEL SCRIPTS -->
	<!-- BEGIN THEME STYLES --> 
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	<!-- END THEME STYLES -->
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>   
	<script type="text/javascript" src="../../assets/zhoujx/zhouuser.js"></script>
	<link rel="shortcut icon" href="favicon.ico" />
	<style>
	html { overflow-x:hidden; }
	.content{height:100%; background:#ffffff; position:absolute; width:100%;} 
	</style>
	<!-- END PAGE LEVEL SCRIPTS -->
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<script src="../../assets/zhoujx/menusort.js" type="text/javascript"></script> 
	<script src="../../assets/zhoujx/menusort-table.js" type="text/javascript"></script> 
	<link href="../../assets/css/menu.css" rel="stylesheet" type="text/css"/>



	<script>
		jQuery(document).ready(function() {   
		//start get the menu ajax
			$.ajax({ 
		        type: "GET",
		        url: "sortmenu1",
		        dataType: "json", 
		        success: function(array){ 
		            if(array['state']=="success"){
		  			$("#username").text(array['username']);
		  				 Menusort.init(array);//load menu
		            }else{
		            if(array['state']=='unlogin')
				        {
					        alert(array['error']);
					        top.location='../../Login/Login/login';
				        }
			   		}
		   				
		        }
			}); 
		});
	</script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed" height="100%" >
	<div class="content">							
			<!-- BEGIN PAGE CONTENT-->
			<div class="row" >
				<div class="col-md-12">
					<div class="portlet box blue" id="form_wizard_1">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-reorder"></i>菜单排序<span class="step-title"></span>
							</div>
						</div>
						<div class="form-actions fluid">
							<div class="row">
								<div class="col-md-12">

									<div style="float:left;margin-top:5px;margin-left:20px;">
										<div style="float:left;">
											<button id="addmenu" align="left" name="sortmenu" type="button" class="btn green pull-right">
														 <span id="addmenu">添加菜单</span>
											</button>
										</div>
									</div>

									<div id="btnmenu" style="float:left;margin-top:5px;margin-left:20px;">
										<div id="menu_tip" style="color:red;width:300px;margin-left:20px;" ><font  id="menu_tip" ></font></div>
									</div>

									<div id="btnback" style="float:left;margin-top:5px;margin-left:20px;display:none">
										<div style="float:left;">
											<button id="backmenu" align="left" name="sortmenu" type="button" class="btn green pull-right">
												 <span id="backmenu">返回</span>
											</button>
										</div>
										<div id="menu_tip" style="color:red;width:300px;margin-left:20px;" ><font  id="menu_tip" ></font></div>
									</div>
								</div>
							</div>
						</div>
	
		<div   style="background:#fff; color:#000;witdh:100%">
			<div id="sort_menu1">
				<div class="portlet box blue">
					<div class="portlet-title">
						<div class="caption"><i class="fa fa-globe"></i>菜单列表
						</div>
					</div>
				</div>
				<table class='table table-striped table-bordered table-hover' id='sort_menu2'>
					<thead>
						<tr role="row" class="heading">
							<th  width="5%">所属模块</th>
							<th  width="5%">菜单ID</th>
							<th  width="10%">菜单名</th>
							<th  width="20%">菜单链接</th>
							<th  width="5%">菜单上级节点ID</th>
							<th  width="5%">菜单显示顺序的级别</th>
							<th  width="5%">是否有视图</th>
							<th  width="5%">编辑</th>
							<th  width="5%">删除</th>
						</tr></thead>
						<tbody></tbody>
						<tfoot></tfoot>
				</table>
			</div>
			


	<div id="menuhead" style="display:none">
				
		<div class="row">
				<div class="col-md-12">
					<div class="tabbable tabbable-custom boxless">
						<div class="tab-content" style="margin:0;padding:0">
							<div class="tab-pane active" style="margin:0" id="tab_0">
								<div class="portlet box blue">
									<div class="portlet-title">
										<div class="caption"><i class="fa fa-globe"></i>菜单表单</div>
									</div>
									<div class="portlet-body form">
										<!-- BEGIN FORM-->
										<form action="#" class="form-horizontal form-row-sepe">
											<div class="form-body">
												<div class="form-group">
													<label  class="col-md-3 control-label">是否属于公共模块</label>
													<div class="col-md-4">
														是：<input type="radio"  checked="checked" name="module" value="0" />
														否：<input type="radio" name="module" value="1" />
														<span class="help-block">如果选无表示属于当前游戏模块</span>
													</div>
												</div>
												<div class="form-group">
													<label  class="col-md-3 control-label">菜单父节点</label>
													<div class="col-md-4">
														<select id="selectmenu" class="form-control input-xlarge select2me select2-offscreen" data-placeholder="Select..." tabindex="-1">
														</select>
														<span class="help-block">
														'无'表示此菜单为一级菜单,没有父节点菜单
														</span>
													</div>
												</div>
												<div class="form-group">
													<label  class="col-md-3 control-label">菜单名称</label>
													<div class="col-md-4">
														<input type="text" name = "menuname"class="form-control" placeholder="例如：首页">
														<span class="help-block">菜单显示的名称</span>
													</div>
												</div>
												<div class="form-group">
													<label  class="col-md-3 control-label">菜单链接</label>
													<div class="col-md-4">
														<input type="text" name = "menuurl" class="form-control" placeholder="例如：www.baidu.com">
														<span class="help-block">菜单点击的链接</span>
													</div>
												</div>
												<div class="form-group">
													<label  class="col-md-3 control-label">菜单显示序号</label>
													<div class="col-md-4">
														<select id="sortidmenu" class="form-control input-xlarge select2me select2-offscreen" data-placeholder="Select..." tabindex="-1">
														<option value="1">1</option>
														<option value="2">2</option>
														<option value="3">3</option>
														<option value="4">4</option>
														<option value="5">5</option>
														<option value="6">6</option>
														<option value="7">7</option>
														<option value="8">8</option>
														<option value="9">9</option>
														</select>
														<span class="help-block">
														同级菜单前后显示依据，按照低优先级显示
														</span>
													</div>
												</div>
												<div class="form-group">
													<label  class="col-md-3 control-label">是否有视图</label>
													<div class="col-md-4">
														有：<input type="radio" checked="checked" name="view" value="1" />
														无：<input type="radio" name="view" value="0" />
														<span class="help-block">是否在菜单栏显示</span>
													</div>
												</div>

												<div class="form-group">
													<label  class="col-md-3 control-label"></label>
													<div class="col-md-4">
														<div id="addmenu_tip" style="color:red;width:300px;min-height:30px;" >
															<font  id="addmenu_tip" ></font>
														</div>
													</div>
												</div>

												<div class="form-actions fluid">
													<div class="col-md-offset-3 col-md-9">
														<button id="submitaddmenu" type="button" class="btn green">提交</button>
														<button type="reset" class="btn default">重置</button>
													</div>
												</div>
											</div>
										</form>
										<!-- END FORM--> 
									</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->    
		</div>
		


















			</div>
		</div>






					</div>
				</div>
			</div>
			<!-- END PAGE CONTENT-->   
		<!-- END PAGE -->  
	</div>
</body>
<!-- END BODY -->
</html>