<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0.2
Version: 1.5.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>Metronic | Form Stuff - Form Components</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->          
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
	
	<!--  
	<link rel="stylesheet" type="text/css" href="../../plugins/gritter/css/jquery.gritter.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/clockface/css/clockface.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-datepicker/css/datepicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-timepicker/compiled/timepicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-colorpicker/css/colorpicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-datetimepicker/css/datetimepicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/jquery-multi-select/css/multi-select.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-switch/static/stylesheets/bootstrap-switch-metro.css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/jquery-tags-input/jquery.tagsinput.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-markdown/css/bootstrap-markdown.min.css">
	-->
	
	<!-- END PAGE LEVEL STYLES -->
	<!-- BEGIN THEME STYLES --> 
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	
	<!-- END THEME STYLES -->
	<link rel="shortcut icon" href="favicon.ico" />
	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	
	<style type="text/css">
		body{
			 background-color: #FFFFFF !important;
		}
	</style>
	
	<script type="text/javascript">
	$(function(){
		$("#cases").change(function(){
			if(this.value != '请选择案例'){
				$.post("getCaseVersion", { "case_id": this.value},function(data){
					var length =data.length;
					var options = "";
					for(var i=0;i<length;i++){
						options +="<option  value='"+data[i].case_v_id+"'>"+data[i].version+"</option>";
								
					}
					$("#caseVersion").children("option").remove();
					$("#caseVersion").append(options)	;
					options = "";
				}, "json");
			}else{
				   $("#caseVersion").children("option").remove();
				   options ="<option  value='请选择案例版本'>"+"请选择案例版本"+"</option>";
				   $("#caseVersion").append(options)	;
			}
			
		});

		//$('#export').click(function(){
		//	var case_v_id = $("#caseVersion").val();
			//if(case_v_id != '请选择案例版本'){
			//	$.post("exportexcel", { "case_v_id": case_v_id});
			//}
			
		//});
		
	});
		

	</script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body>
	<div class="www">
			<h3 class="page-title">

				&nbsp;&nbsp;&nbsp;Test Case <small>excel output</small>
			</h3>
		</div>
	<!-- BEGIN HEADER -->   
	
	<!-- END HEADER -->
	<!-- BEGIN CONTAINER -->

		<!-- BEGIN SIDEBAR -->
		
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->  
		<div class="page-content" style="margin-left: 0; margin-bottom:0; min-height:960px;padding:0 0 0 0 ;">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->               
			<div class="modal fade" id="portlet-config"  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Modal title</h4>
						</div>
						<div class="modal-body">
							Widget settings form goes here
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Save changes</button>
							<button type="button" class="btn default" data-dismiss="modal">Close</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			
		
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN PORTLET-->   
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-reorder"></i>Excel  Output </div>
							<div class="tools">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							
							<form  action='exportexcel' class="form-horizontal form-bordered" method='post'>
						
								<div class="form-body">
									
									<div class="form-group">
										<label class="control-label col-md-3">Export File</label>
										<div class="col-md-9">
											<div class="fileupload fileupload-new" data-provides="fileupload">
												<div class="input-group">
													
													
													<span class="btn default btn-file">
													<span class="fileupload-new" ><i class="fa fa-paper-clip"></i> 案例 </span>
																<select style="length:120px" id='cases'>
																	<option value='请选择案例'> 请选择案例</option>
																	  <?php 
																	  	if(!empty($cases)){
																	  		for($i = 0; $i <count($cases);$i++){
																	  			
																	  	?>
																	  		<option value='<?=$cases[$i]['case_id']?>'> <?=$cases[$i]['casename'] ?> </option>
																	  		
																	  	<?php 
																	  				
																	  			
																	  		}
																	  	}
																	  
																	  ?>
																</select>
															<span class="fileupload-new" ><i class="fa fa-paper-clip"></i> 案例版本 </span>	
																<select style="length:120px" id="caseVersion" name='case_v_id'>
																	<option value='请选择案例版本'> 请选择案例版本</option>
																 
																</select>
													</span>
													
												</div>
											</div>
										</div>
									</div>
							     
								</div>
								<div class="form-actions fluid">
									<div class="row">
										<div class="col-md-12">
											<div class="col-md-offset-3 col-md-9">
												<button  type="submit" id='export' class="btn purple"><i class="fa fa-check"></i> Submit</button>
												                             
											</div>
										</div>
									</div>
								</div>
							 
							</form>
						
							<!-- END FORM-->  
						</div>
					</div>
					<!-- END PORTLET-->
				</div>
			</div>
		 
			<!-- END PAGE CONTENT-->   
		</div>
		<!-- END PAGE -->  

	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	
	<!-- END FOOTER -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->   
	<!--[if lt IE 9]>
	<script src="../../plugins/respond.min.js"></script>
	<script src="../../plugins/excanvas.min.js"></script> 
	<![endif]-->   
	<!--  
		<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	-->
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>     
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../../plugins/bootstrap/js/bootstrap2-typeahead.min.js" type="text/javascript"></script>
	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	
	<!-- 
	<script type="text/javascript" src="../../plugins/fuelux/js/spinner.min.js"></script>
	<script type="text/javascript" src="../../plugins/ckeditor/ckeditor.js"></script>  
	 -->
	 
	<script type="text/javascript" src="../../plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
	
	<!--
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script> 
	<script type="text/javascript" src="../../plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
	<script type="text/javascript" src="../../plugins/clockface/js/clockface.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-daterangepicker/moment.min.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-daterangepicker/daterangepicker.js"></script> 
	<script type="text/javascript" src="../../plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>  
	<script type="text/javascript" src="../../plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
	<script type="text/javascript" src="../../plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>   
	<script type="text/javascript" src="../../plugins/jquery.input-ip-address-control-1.0.min.js"></script>
	  -->
	
	<!-- 
	<script type="text/javascript" src="../../plugins/jquery-multi-select/js/jquery.multi-select.js"></script>
	<script type="text/javascript" src="../../plugins/jquery-multi-select/js/jquery.quicksearch.js"></script>   
	<script src="../../plugins/jquery.pwstrength.bootstrap/src/pwstrength.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-switch/static/js/bootstrap-switch.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-tags-input/jquery.tagsinput.min.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-markdown/lib/markdown.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript" ></script>
	 -->
	 
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../../scripts/app.js"></script>
	<!-- 
		<script src="../../scripts/form-components.js"></script>    
	 -->
	 
	<!-- END PAGE LEVEL SCRIPTS -->
	<script>
		jQuery(document).ready(function() {       
		   // initiate layout and plugins
		   App.init();
		   //FormComponents.init();
		});
	</script>
	<!-- BEGIN GOOGLE RECAPTCHA -->
	<script type="text/javascript">
		var RecaptchaOptions = {
		   theme : 'custom',
		   custom_theme_widget: 'recaptcha_widget'
		};
	</script>
	
	<!-- END GOOGLE RECAPTCHA -->
	<!-- END JAVASCRIPTS -->   
</body>
<!-- END BODY -->
</html>