<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0.2
Version: 1.5.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>Metronic | Data Tables - Ajax Datatables</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->          
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<!-- END PAGE LEVEL STYLES -->
	<!-- BEGIN THEME STYLES --> 
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	<!-- END THEME STYLES -->
	<link rel="shortcut icon" href="favicon.ico" />
	
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-fileupload/bootstrap-fileupload.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/gritter/css/jquery.gritter.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/clockface/css/clockface.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-datepicker/css/datepicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-timepicker/compiled/timepicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-colorpicker/css/colorpicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-datetimepicker/css/datetimepicker.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/jquery-multi-select/css/multi-select.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-switch/static/stylesheets/bootstrap-switch-metro.css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/jquery-tags-input/jquery.tagsinput.css" />
	<link rel="stylesheet" type="text/css" href="../../plugins/bootstrap-markdown/css/bootstrap-markdown.min.css">
	<!-- END PAGE LEVEL STYLES -->
	
	
	
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
	<!-- BEGIN HEADER -->   
	<h3 class="page-title">

				&nbsp;&nbsp;&nbsp;日志查看
	</h3>
	<!-- END HEADER -->
	<div class="clearfix"></div>
	<!-- BEGIN CONTAINER -->
	<div class="page-container">
		<!-- BEGIN SIDEBAR -->
		
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->
		<div class="page-content"  style="margin-left: 0; margin-bottom:0;padding:0 0 0 0 ;">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->               
			<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Modal title</h4>
						</div>
						<div class="modal-body">
							Widget settings form goes here
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Save changes</button>
							<button type="button" class="btn default" data-dismiss="modal">Close</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
	
			<!-- END BEGIN STYLE CUSTOMIZER -->            
			<!-- BEGIN PAGE HEADER-->
			<div class="row">
				
			</div>
			<!-- END PAGE HEADER-->
			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption"><i class="fa fa-edit"></i>日志记录</div>
							
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
								
								<!-- 
									<button id="sample_editable_1_new" class="btn green">
									Add New <i class="fa fa-plus"></i>
									</button>
								 -->
								 
								</div>
								
								<div class="btn-group pull-right">
								
								<!--  
									<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
									</button>
									<ul class="dropdown-menu pull-right">
										<li><a href="#">Print</a></li>
										<li><a href="#">Save as PDF</a></li>
										<li><a href="#">Export to Excel</a></li>
									</ul>
								-->
								
								</div>
							</div>
							
							<div class="form-group">
										<label class="control-label col-md-3">选择时间查看</label>
										<div class="col-md-4">
											<div class="input-group input-large date-picker input-daterange" data-date="10/11/2012" data-date-format="mm/dd/yyyy">
												<input type="text" class="form-control" name="from" id="fromtime">
												<span class="input-group-addon">to</span>
												<input type="text" class="form-control" name="to" id="toTime">
											</div>
											<!-- /input-group -->
											<span class="help-block"></span>
										</div>
										<button type="submit" class="btn purple" id="querybutton"><i class="fa fa-check"></i> Submit</button>
							</div>
							
							<!-- 表格区 -->
						<div id="logTable">
							<table class="table table-striped table-bordered table-hover" id="sample_1">
								<thead>
									<tr>
										<th>用户ID</th>
										<th>描述</th>
										<th>日志时间</th>
									</tr>
								</thead>
								<tbody></tbody>
							</table>
							<!-- 表格区 -->
						</div>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
			<!-- END PAGE CONTENT -->
		</div>
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	<div class="footer">
		<div class="footer-inner">
			2013 &copy; Metronic by keenthemes.
		</div>
		<div class="footer-tools">
			<span class="go-top">
			<i class="fa fa-angle-up"></i>
			</span>
		</div>
	</div>
	<!-- END FOOTER -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->   
	<!--[if lt IE 9]>
	<script src="../../plugins/respond.min.js"></script>
	<script src="../../plugins/excanvas.min.js"></script> 
	<![endif]-->   
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script src="../../plugins/bootstrap/js/bootstrap2-typeahead.min.js" type="text/javascript"></script>
	

	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script type="text/javascript" src="../../plugins/fuelux/js/spinner.min.js"></script>
	<script type="text/javascript" src="../../plugins/ckeditor/ckeditor.js"></script>  
	<script type="text/javascript" src="../../plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script> 
	<script type="text/javascript" src="../../plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
	<script type="text/javascript" src="../../plugins/clockface/js/clockface.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-daterangepicker/moment.min.js"></script>
	<script type="text/javascript" src="../../plugins/bootstrap-daterangepicker/daterangepicker.js"></script> 
	<script type="text/javascript" src="../../plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>  
	<script type="text/javascript" src="../../plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
	<script type="text/javascript" src="../../plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>   
	<script type="text/javascript" src="../../plugins/jquery.input-ip-address-control-1.0.min.js"></script>
	<script type="text/javascript" src="../../plugins/jquery-multi-select/js/jquery.multi-select.js"></script>
	<script type="text/javascript" src="../../plugins/jquery-multi-select/js/jquery.quicksearch.js"></script>   
	<script src="../../plugins/jquery.pwstrength.bootstrap/src/pwstrength.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-switch/static/js/bootstrap-switch.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-tags-input/jquery.tagsinput.min.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-markdown/lib/markdown.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript" ></script>
	<script src="../../plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript" ></script>
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src="../../scripts/app.js"></script>
	<script src="../../assets/wgy/queryAllUserLog.js"></script>
	<script src="../../scripts/form-components.js"></script>   
	<script>
		jQuery(document).ready(function() {  
		
			$.post("queryuseralllog",function(data,status){
				 TableAjax.init(data);
				},"json");
			
			FormComponents.init();

			$("#querybutton").click(function(){
				var fromTime = $("#fromtime").val();
				var toTime = $("#toTime").val();
				$("#logTable").empty();
				var newTable="<table class=\"table table-striped table-bordered table-hover\" id=\"sample_1\">"
								+"<thead>"
									+"<tr>"
										+"<th>用户ID</th>"
										+"<th>描述</th>"
										+"<th>日志时间</th>"
								    +"</tr>"
								+"</thead>"
								+"<tbody></tbody>"
							"</table>";
				$("#logTable").html(newTable);
				$.post("querylogbytime",{"fromTime":fromTime,"toTime":toTime},function(data,status){
					 TableAjax.init(data);
					},"json");
				
			});
			
		  
		});
	</script>
</body>
<!-- END BODY -->
</html>