<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- <link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" /> -->
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色-->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../scripts/jquery-1.11.0.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2.css">
	<script type="text/javascript" src="../../plugins/select2/select2.js"></script>
<!-- 	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script> -->
<!-- 	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>   -->
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
<!-- 	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script> -->
	<!-- datatable的js -->
	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script>

	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<script src="../../scripts/app.js" type="text/javascript"></script>
	<script src="../../assets/chengh/table-editable.js" type="text/javascript"></script>    
	<script>
		jQuery(document).ready(function() {       
		   App.init();
		   var data = <?php echo $json ?>;
		   TableEditable.init(data);
		});



	</script>
<style type="text/css">
.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
</style>
</head>	
<body>
<div class="www">
		<h3 class="page-title">
						测试任务创建及分配 <small>form zwcs</small>
		</h3>
<input type="text" style="display:none" value="<?php echo $game_v_id?>" id="game_v_id"/>
<div class="portlet box blue">
<div class="portlet-title">
	<div class="caption" id = title><i class="fa fa-globe"></i>任务创建分配<a class="btn blue" href="cosGameVersion?game_id=<?php echo $game_id?>" target="page_iframe">
			<i class="fa fa-reply"></i>
			返回上一层</a></div>

</div>
<div class="portlet-body">
	
		<div class="table-toolbar">
			<div class="btn-group">
				<button id="sample_editable_1_new" class="btn green">
				Add New <i class="fa fa-plus"></i>
				</button>
			</div>

		</div>
	

		<table id="sample_editable_1"  class="table table-striped table-hover table-bordered">
			<thead>
				<tr>
					<td>任务名</td>
					<td>任务详细信息</td>
					<td>测试者</td>
					<td>taskId</td>
					<td>查看任务</td>
					<td>编辑</td>
					<td>删除</td>
				</tr>
			</thead>
			<tbody>
			</tbody>

		</table>

<a id="goTop" href="#top"></a>
</div>
</div>
</div>
</body>
</html>