<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0.2
Version: 1.5.4
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>Metronic | Pages - Timeline</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<meta name="MobileOptimized" content="320">
	<!-- BEGIN GLOBAL MANDATORY STYLES -->          
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN THEME STYLES --> 
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/pages/timeline.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../css/custom.css" rel="stylesheet" type="text/css"/>
	<!-- END THEME STYLES -->
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>  
	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script>
	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
	<script src="../../assets/zhoujx/zhounote.js" type="text/javascript"></script>
	<script>
		jQuery(document).ready(function() {   
		//start get the menu ajax
			$.ajax({ 
		        type: "GET",
		        url: "getnote", 
		        dataType: "json", 
		        success: function(array){ 
		            if(array['state']=="success"){
		  				 Note.init(array);//load Note
		            }else{
		            	if(array['state']=='error')
				        {
					        alert(array['error']);
				        }
			   		}
		   				
		        }
			}); 
		});
	</script>
		<style>
	html { overflow-x:hidden; }
	.notecss{height:100%; background:#ffffff; position:absolute; width:100%;} 
	</style>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">   
	<div class="notecss">        
		<div class="row" >
				<div class="col-md-12">
					<div class="portlet box blue" id="form_wizard_1">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-reorder"></i>My Note<span class="step-title"></span>
							</div>
							<div class="tools hidden-xs">
								<a href="javascript:;" class="collapse"></a>
								<a href="#portlet-config" data-toggle="modal" class="config"></a>
								<a href="javascript:;" class="reload"></a>
								<a href="javascript:;" class="remove"></a>

							</div>
						</div>
						<div style="margin:0 0 0 1%;">
							<a href="javascript:;" id="addnote" class="btn green button-submit">
							<span >添加</span> <i class="m-icon-swapright m-icon-white"></i></a>
						</div>
						<div class="form-actions fluid">
							<div class="row">
								<div class="col-md-12">
									<ul class="timeline" id="zhou_mynote">
									</ul>
								</div>
							</div>

					<form action="#" class="form-horizontal" id="zhou_addnote" height="860px" style="display:none;background-color:#f5f5f5;margin:0 0 0 2%;">
								<div class="form-wizard">
									<div class="form-body">
										<div class="tab-content">
											<div class="tab-pane active" id="tab1">
												<h3 class="block">Provide your Note details</h3>
												<div class="form-group">
													<label class="control-label col-md-3">Title<span class="required">*</span></label>
													<div class="col-md-4">
														<input id="note_title"  type="text" class="form-control" name="username"/>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">Content<span class="required">*</span></label>
													<div class="col-md-4">
														<textarea  rows="10" cols="100" name="password" id="note_content">
														</textarea>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">Remarks</label>
													<div class="col-md-4">
														<textarea rows="5" cols="100"name="password" id="note_remarks">
														</textarea>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3"></label>
													<div class="col-md-4">
													<div  align="left"style="color:red"><font  id="addnote_tip" > </font>&nbsp;</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="form-actions fluid">
										<div class="row">
											<div class="col-md-12">
												<div class="col-md-offset-3 col-md-9">
													<a href="javascript:;" id="zhou_addnotesubmit" class="btn green button-submit">
													<span id="addsubmit">Submit</span> <i class="m-icon-swapright m-icon-white"></i>
													</a>  
													<a style="margin:0 0 0 3%"href="javascript:;" id="backnote" class="btn green button-submit">
													<span >back</span> <i class="m-icon-swapright m-icon-white"></i>
													</a>                             
												</div>

											</div>
										</div>
									</div>
								</div>
			</form>
						</div>
						
					</div>
				</div>
			<!--start show note-->

			<!--end show note-->

			<!--start add note-->
			<!--end add note-->
			<!-- END PAGE CONTENT-->
		<!-- END PAGE -->    
		</div> 
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->   
	<!--[if lt IE 9]>
	<script src="../../plugins/respond.min.js"></script>
	<script src="../../plugins/excanvas.min.js"></script> 
	<![endif]-->   
	<!-- END CORE PLUGINS -->
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>