<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色-->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../assets/css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<!-- 	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script> -->
<!-- 	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>   -->
<!-- 	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script> -->
	<!-- datatable的js -->
<!-- 	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script> -->
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<!-- // <script type="text/javascript" src="../../scripts/special_privilege.js"></script> -->
	
	<script type="text/javascript" src="../../assets/songgl/genTree.js"></script>
	<script type="text/javascript" src="../../assets/songgl/group_manage.js"></script>
	<style type="text/css">
		.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
	</style>
</head>	
<body>
<div class="www">
		<h3 class="page-title">
						权限组管理<small>form zwcs</small>
		</h3> 
<input type='text' style='display: none' value=<?php echo $user_id?> id='user_id'/>
<!-- Form ***************************新增**********************************-->
<form id="in_form" action="#" method="post" class="form-horizontal form-bordered" onsubmit="javascript:return false;">
<div class="form-body">
	<div class="modal fade in modal-overflow" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
				<div class="modal-dialog" style="width: 1100px; height: 550px">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">新建组</h4>
						</div>
						<div class="modal-body">
							<div class="row">
									<div class="col-md-6">
										<h5>组名称</h5>
										<p><input class="col-md-6 form-control " type="text" id="add_group_name"></p>
									</div>	
									<div class="col-md-6" >
										<h5>所属模块</h5>
										<p><select class="col-md-5 form-control" id="add_module_id">

										</select></p>
									</div>	
							</div>
							<div class="row">
									<div class="col-md-12">
										<h5>选择菜单</h5>
										<div style="border:solid #93C3F0 1px" id="add_menus_div">
											
										</div>
									</div>	
							</div>						
						</div>
						<div class="modal-footer">
						  <button id="submitbtn" type="button" class="btn blue"  onclick="addGroup();">保存</button> 	
							<button id="closebtn_add" type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
</div>		
</form>
<!-- Form *********************编辑*******************************-->
<form id="edit_form" action="#" method="post" class="form-horizontal form-bordered" onsubmit="javascript:return false;">
<div class="form-body">
	<div class="modal fade in modal-overflow" id="portlet-config-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
				<div class="modal-dialog" style="width:1100px">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">编辑组</h4>
						</div>
						<div class="modal-body">
							<div class="row">
									<div class="col-md-2">
										<h5>组名称</h5>
										<input style="display:none" id="edit_hidden_group_id">
										<p><input class="col-md-3 form-control " type="text" id="edit_group_name"></p>
									</div>	
									<div class="col-md-6" >
										<!-- <h5>所属模块</h5>
										<p><select class="col-md-5 form-control" id="module_id">

										</select></p> -->
									</div>	
							</div>
							<div class="row">
									<div class="col-md-12">
										<h5>组内权限</h5>
										<div style="border:solid #93C3F0 1px" id="edit_menus_div">
											
										</div>
									</div>	
							</div>						
						</div>
						<div class="modal-footer">
						  <button id="submitbtn" type="button" class="btn blue"  onclick="saveGroup()">保存</button> 	
							<button id="closebtn_edit" type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
</div>		
</form>
<!-- Form ***************************************************************-->







<div class="portlet blue box">
	<!-- <div class="portlet-title">
		<div class="caption"><i class="fa fa-cogs"></i>权限组管理</div>
	</div> -->

	<div class="portlet-title">
	<div class="caption"><i class="fa fa-cogs"></i>权限组管理</div>
		<div class="actions">
		<a id="addbtn" class="btn blue" href="#portlet-config" data-toggle="modal" onclick="showAddGroupPage();">
			<i class="fa fa-plus"></i>
			添加组
		</a> 
		<!-- <a id="delete" class="btn blue" href="#" onclick="fnDeleteRows();">
			<i class="fa fa-minus"></i>
			批量删除
		</a> -->
		<a class="btn blue" href="#" onclick="reload();">
			<i class="fa fa-refresh"></i>
			刷新
		</a>
		</div>
	</div>


	<div class="portlet-body" id="">
		<div>
	<table class="table table-striped table-bordered table-hover" id="table_id" >
	<thead id="thead">	
		<tr>
			<th width="5%"><input type="checkbox" id="allCheckbox"></th>
			<th><p align="center">组名称</p></th>
			<th><p align="center">所属模块</p></th>
			<th width="10%"><p align="center">组内用户</p></th>
			<th width="10%"><p align="center">编辑组内权限</p></th>
			<th width="10%"><p align="center">删除该组</p></th>
		</tr>
	</thead>
	<tbody id="tbody"></tbody>
	<tfoot></tfoot>
</table>
	</div>
	</div>
	<div id="user_in_group" style="background:white">
		

	</div>
</div>

</div>
</body>
</html>