<html>
<head>
	<!-- 框架的css ****************************************************************************************-->
	<!-- 这个css是显示前后翻页图标的 -->
	<link href="../../plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	
	<link href="../../plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	<link href="../../plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" type="text/css" href="../../plugins/select2/select2_metro.css" />
	<link rel="stylesheet" href="../../plugins/data-tables/DT_bootstrap.css" />
	<link href="../../css/style-metronic.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/style-responsive.css" rel="stylesheet" type="text/css"/>
	<link href="../../css/plugins.css" rel="stylesheet" type="text/css"/>
	<!-- 下面的主题修改了页面的背景颜色-->
	<link href="../../css/themes/light.css" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="../../assets/css/custom.css" rel="stylesheet" type="text/css"/>
	
	<link rel="shortcut icon" href="favicon.ico" />
	<!-- *********************************************************************************************** -->
	<!-- jquery以及整体bootstrasp框架的js -->	
	<script src="../../plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="../../plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
	<script src="../../plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<!-- 	<script src="../../plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script> -->
<!-- 	<script src="../../plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/jquery.blockui.min.js" type="text/javascript"></script>   -->
<!-- 	<script src="../../plugins/jquery.cookie.min.js" type="text/javascript"></script> -->
<!-- 	<script src="../../plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script> -->
	<!-- datatable的js -->
<!-- 	<script type="text/javascript" src="../../plugins/select2/select2.min.js"></script> -->
	<script type="text/javascript" src="../../plugins/data-tables/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="../../plugins/data-tables/DT_bootstrap.js"></script>
	
	<script type="text/javascript" src="../../scripts/jquery.jeditable.js"></script>
	<!-- // <script type="text/javascript" src="../../scripts/privilege.js"></script> -->
	<script type="text/javascript" src="../../assets/songgl/privilege.js"></script>
	
<style type="text/css">
.www {height:100%; background:#ffffff; position:absolute; width:100%;} 
</style>
</head>	
<body>
<div class="www">
		<!-- <h3 class="page-title">
						Privilege <small>form zwcs</small>
		</h3> -->
		<ul class="page-breadcrumb breadcrumb">
			<li>
				<i class="fa fa-home"></i>
				<a href="#">首页</a> 
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="#">权限管理</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li><a href="#">权限分配</a></li>
		</ul>
<!-- <input type="text" style="display: none" value=<?php echo $tc_testcase_id?> id="tc_testcase_id"/> -->
<input type='text' style='display: none' value=<?php echo $user_id?> id='user_id'/>

<!-- 对话框 -->
<form id="in_form" action="#" method="post" class="form-horizontal form-bordered" onsubmit="javascript:return false;">
<div class="form-body">
	<div class="modal fade in modal-overflow " id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog" style="width: 750px; height: 550px">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">创建测试用例</h4>
						</div>
						<div class="modal-body">
							<div class="row">
									<div class="col-md-6">
										
									</div>	
							</div>						
						</div>
						<div class="modal-footer">
						  <button  id="submitbtn" type="button"  class="btn blue"  data-dismiss="modal" >保存</button> 	
							<button  id="closebtn" type="button" class="btn default" data-dismiss="modal">关闭</button>
						</div>
					</div>
				</div>
			</div>
</div>		
</form>
<!-- 对话框 -->

<!-- CRUD按钮 -->
<!--
<div class="portlet box blue">
	<div class="portlet-title">
	<div class="caption"><i class="fa fa-globe"></i>个人特殊权限</div>
		<div class="actions">
		<a  id="addbtn" class="btn blue" href="#portlet-config"  data-toggle="modal" class="config"  onClick="clearForm();">
			<i class="fa fa-plus"></i>
			Add
		</a>
		-->
		<!-- <a id="editbtn" class="btn blue" href="#portlet-config"  data-toggle="modal" class="config" onClick="fnEditRow();"> -->
		<!--
		<a id="editbtn" class="btn blue" href="#portlet-config"  data-toggle="modal" class="config" onClick="changeClickEvent();">
			<i class="fa fa-edit"></i>
			Edit
		</a>
		<a id="delete" class="btn blue" href="#" onClick="fnDeleteRows();">
			<i class="fa fa-minus"></i>
			Delete
		</a>
		<a class="btn blue" href="#" onClick="reload();">
			<i class="fa fa-refresh"></i>
			Reload
		</a>
		<a id="delete" class="btn blue" href="#" onClick="exportCases();">
			<i class="fa fa-download"></i>
			Export
		</a>
		<a class="btn blue" href="#" id="versionbtn" onclick="extendVersion()">
			<i class="fa  fa-hand-o-right"></i>
			Extend Version List
		</a>
		</div>
	</div>
	<div class="portlet-body">
		
	</div>
</div>
-->
<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption"><i class="fa fa-reorder"></i>自己已有权限</div>
	</div>
	<div class="portlet-body">
		<div id="content"></div>
	</div>
</div>


<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption"><i class="fa fa-reorder"></i>查询用户&授权</div>
	</div>
	<div class="portlet-body">
		<div class="input-group input-large">
			<input  id="user_id_input" type="text" class="form-control" placeholder="请输入要授权的用户工号">
			<span class="input-group-btn">
			<button class="btn blue" type="button" id="user_id_btn">查询</button>
			<button class="btn green" type="button" id="modify">修改</button>
			</span>
		</div>
		<span id="targetName_span"></span>
	</div>
</div>


<!-- <div class="col-md-6">
<div class="portlet blue box">
	<div class="portlet-title">
		<div class="caption"><i class="fa fa-cogs"></i>权限分组</div>
	</div>
	<div class="portlet-body">
		<div class="form-group">
			<label>游戏</label>
				<select class="form-control input-medium" id="module_select">
					<option value="-1">选择要分配权限的游戏或者模块</option>
				</select>
		</div>
	</div>
</div>
</div>
<div class="col-md-6">
<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption"><i class="fa fa-reorder"></i>Portlet</div>
	</div>
	<div class="portlet-body">
			
	</div>
</div>
</div> -->
</div>
</body>
</html>